---
- name: Install MongoDB
  hosts: default
  become: true
  tasks:
    - name: Add Repo key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927

    - name: Add a line to a file of sources
      lineinfile:
        path: /etc/apt/sources.list.d/mongodb-org-3.2.list
        line: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
        create: yes

    - name: Install package
      apt:
        name: mongodb-org
        update_cache: yes

    - name: enable service
      systemd:
        name: mongod
        enabled: yes
