- name: Clone
  hosts: db
  tasks:
    - name: Clone repo
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/appuser/reddit
    - name: Uptime
      command: "uptime"
  
