plugin: gcp_compute
projects:
  - infra-244506
auth_kind: serviceaccount
service_account_file: ~/infra-244506-f3d242c52a39.json
scopes:
  - 'https://www.googleapis.com/auth/compute.readonly'
hostnames:
  - name
groups:
  app: "'app' in name"
  db: "'db' in name"
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
